[package]
name = "emu"
version = "0.1.0"
authors = ["Tom Arrell <tom.arrell@gmail.com>"]
edition = "2018"

[dependencies]
clap = { version = "2.33.0", features = ["yaml"] }
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }
dirs = "1.0.5"
regex = "1.5.5"
